export const MEMORY_LIMITS = {
  SHORT_TERM: 50,
  LONG_TERM: 1000,
  VECTOR_DIMENSIONS: 1536
};

export const SERVICE_CONFIG = {
  DEFAULT_TIMEOUT: 30000,
  MAX_RETRIES: 3,
  CACHE_TTL: 3600
};

export const WEBSOCKET_CONFIG = {
  PORT: 8080,
  HEARTBEAT_INTERVAL: 30000,
  RECONNECT_DELAY: 5000
};

export const API_CONFIG = {
  BASE_URL: process.env.NEXT_PUBLIC_API_URL || 'http://localhost:3000',
  TIMEOUT: 10000,
  RETRIES: 3
}; 